FROM golang:1.21-alpine AS builder

WORKDIR /build
COPY go.* .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o auth-service

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /build/auth-service /app/
WORKDIR /app

RUN adduser -D -H -h /app appuser
USER appuser

EXPOSE 8080 9090
ENTRYPOINT ["/app/auth-service"]